---
---
- hosts: web_servers
  gather_facts: no
  roles:
    - role: nginx
      vars:
        nginx_redhat_nginx_version: "1.26.0"
    - role: rebrain-web-std
      vars:
        nginx_redhat_log_format : '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
        company: rebrain
