---
- name: Change default nginx.conf
  become: yes
  block:
    - name: Copy template nginx.conf to server
      template:
        src: nginx_conf.j2
        dest: "/etc/nginx/nginx.conf"

    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: reloaded

- name: Change default index.html
  become: yes
  block:
    - name: Copy template nginx.conf to server
      template:
        src: index_html.j2
        dest: "/usr/share/nginx/html/index.html"

    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: reloaded
